application:
  dynamo:
    region: "eu-west-1"
    table: "OnlineShop"
    endpoint: "https://dynamodb.eu-west-1.amazonaws.com"

cognito-domain: ${cognito_domain}

logging:
  level:
    org:
      springframework:
        web: DEBUG

cognito:
  redirect-uri: ${cognito_redirect_uri}
  client-id: ${cognito_client-id}
  client-secret: ${cognito_client-secret}
  endpoint: https://${cognito-domain}_auth_eu-west-1_amazoncognito_com
  pool-id: ${cognito_pool-id}

spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            provider: cognito
            client-id: ${cognito_client_id}
            client-secret: ${cognito_client_secret}
            client-name: Cognito
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: ${cognito_redirect_uri}:${server_port}/login/oauth2/code/cognito
        provider:
          cognito:
            authorization-uri: ${cognito_endpoint}/oauth2/authorize
            token-uri: ${cognito_endpoint}/oauth2/token
            user-info-uri: ${cognito_endpoint}/oauth2/userInfo
            jwk-set-uri: https://cognito-idp_eu-west-1_amazonaws_com/${cognito_pool_id}/_well-known/jwks_json
            userNameAttribute: cognito:username
